name: geniusmedia
favicon: null
layout_spectrum: 0.1020566828083247
typography_spectrum: 0.6306855892762542
title: geniusmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfafa'
    - '#ffeeee'
    - '#ff0000'
    - '#ffd5d5'
    - '#ebebeb'
  brandStrength: 0.9456551959738135
  lightness: 0.7673475716728717
  saturation: 0.937903753714636
  rhythmicContrast: 0.6750278491526842
purpose: []
