name: geniusmedia
favicon: null
layout_spectrum: 0.48619
typography_spectrum: 0.51183
title: geniusmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#aaaaaa'
    - '#808080'
    - '#3d3d3d'
  brandStrength: 0.875
  lightness: 0.7673475716728717
  saturation: 0.937903753714636
  rhythmicContrast: 0.6750278491526842
purpose: []
